### ISSUE TITLE
[Enhancement] Widen Access

### ISSUE THREAD

**Issue by BobVarioa** [High-Fox/InventoryActions#1]
### Description
Widen access to [this](https://github.com/High-Fox/InventoryActions/blob/e4faa2a2500c46743764b0eaa770f2ba2df081ed/src/main/java/com/highfox/inventoryactions/util/ActionHandler.java#L34) property to allow other mods (or psuedo mods such as those created by kubejs) to create extensions to your system. Of course with this change you would also have to change the type to a typical Set versus ImmutableSet.

**Comment by High-Fox** [comment]
Oh fair point, I forgot to consider other mods being able to potentially add on to it. I'll probably also make the system simpler and more compatible for other mods to use.
