### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Apiterbakar** [High-Fox/InventoryActions#2]
[crash-2023-01-29_14.10.34-fml.txt](https://github.com/High-Fox/InventoryActions/files/10529248/crash-2023-01-29_14.10.34-fml.txt)

**Comment by High-Fox** [comment]
Ah I accidentally put the wrong version info in the 1.19.2 version. Just fixed it and uploaded the updated version which you can find [here](https://www.curseforge.com/minecraft/mc-mods/inventory-actions/files/4370370)

**Comment by Apiterbakar** [comment]
thanks
